### ISSUE TITLE
Deprecation of `Stream`

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [ocaml-community/yojson#129]
While we did a good job for the OCaml 5.0 readiness by removing `biniou` and `easy-format` OCaml 4.14 will deprecate the `Stream` module.

We should consider what to do:
  1. Use the `camlp-stream` polyfill that provides this module
  2. Migrate to something else like `Seq`

The issue with 1. is that we're adding another dependency. It's probably not a big problem, but it is still not great to depend on something that was removed from the standard library, for most likely good reasons.

The problem with 2. is that this might decrease the performance and since it breaks the interface, it would need to happen for 2.0.0 (or 3.0.0…).

**Comment by Leonidas-from-XIV** [comment]
After discussing this with @NathanReb and @panglesd we agreed that for 2.0.0 it would be sufficient to depend on `camlp-stream` and deprecate the `Stream.t` APIs after 2.0.0.

As such I created a PR to allow us to depend on `camlp-stream` for all our supported OCaml versions: https://github.com/ocaml/camlp-streams/pull/3

**Comment by gasche** [comment]
I'm pretty sure that moving to `Seq` will *improve* performance for your use-case, not *decrease* it. It also looks like a trivial code change. On the other hand, `Seq` was only added in 4.07, so you would need another clutch library for older OCaml versions.

**Comment by Leonidas-from-XIV** [comment]
Or alternatively, since we're breaking compatibility, just move to 4.08 for a 3.0.0 release. But yes, I don't consider this a permanent solution.

**Comment by gasche** [comment]
I think a sensible choice would be to move from `Stream` to `Seq` (it's very simple; do you want a PR?) and update the version requirement to 4.07 accordingly, for 2.00 if it's not out already. When is your next major-bump-release planned?

**Comment by Leonidas-from-XIV** [comment]
I wouldn't want to bump the requirement up from 4.02 to 4.07 for 2.0.0 since we're nearing release and this is mostly a "get rid of ancient dependencies" release, so people who used to use it can just continue to use it, even if they need to support older versions of OCaml. OTOH, if there is some shim-library to retrofit `Seq`, that would be completely alright for 2.0.0.

I guess we plan to release it "real soon"- so far @panglesd has been inspecting how much of the ecosystem will break if we release it as-is now.

**Comment by gasche** [comment]
[stdcompat](https://github.com/thierry-martinez/stdcompat) has a `Seq` implementation starting from OCaml 3.08, so you should be good to go.

My thoughts:
- I certainly don't want to mess with the ongoing release process, that is stressful.
- But I think that the correct long-term change is to *replace* `Stream` with something else, not keep it around, because no one should use this module anymore outside camlp{4,5}.
- I think the right time to do the replacement is *now*, instead of going through pains with camlp-streams in an intermediate period; this will be a compatibility-breaking change, so you could have a 3.0 right after 2.0, which I guess is fine?

**Comment by c-cube** [comment]
I'm just going to say that the `seq` compat shim is absolutely tiny and is a no brainer dependency in my book (and in containers). :-)

**Comment by NathanReb** [comment]
I agree `Stream` should not be kept around in the long run. It's not our plan to do so but since we didn't really plan on this we were pondering whether we could keep it around for 2.0.0 while still allowing yojson to be compatible with OCaml 5.0.

At first I thought `camlp-streams` would act as some kind of reverse shim but it redefines `Stream` no matter what so it's not strictly speaking compatible with OCaml < 5.0's `Stream`.

About moving to `Seq` I think we'd be perfectly happy to do so if that's what people tend to use in place of `Stream`. That's what I would personally do but having a bit of community feedback here would soothe my mind.
We could also drop `Stream` without adding `Seq` directly, this can easily be done in a later minor release if we need more time to think about it.

CC @Leonidas-from-XIV, what do you think?

**Comment by Leonidas-from-XIV** [comment]
I think that @gasche's #131 convinced me that the migration to `Seq` is worth it. It is both faster and actually properly part of the stdlib (and not just a left-over from the time Camlp4 was split out). Even if we were to keep `Stream` for 2.0.0 it would make sense to replace it with *something* later on so that API breakage will always happen - sooner or later.

The only downside is that if we do this in 2.0.0 we don't include any time for deprecation of the old APIs. Though we didn't do this when removing `Bi_outbuf.t` either and maybe it is better to just do all these breaking changes related to external libraries at once instead of forcing people through a number of breaking changes all the time. The fact that we use `Buffer` and `Seq` should be good enough for the next 5+ years, eventually we could as well upgrade to 4.08 as lowest version in the future and avoid the shim library altogether.

So yeah, :+1: for #131 , :-1: for #130 from me.

**Comment by c-cube** [comment]
I agree with @Leonidas-from-XIV. Besides, this is a 2.0, it's fine to break some edge cases. People can stay on 1.7 for a long, long time if they need to (like python 2.7, in a way).
