### ISSUE TITLE
Parsing and serializing issue with some LOCALE

### ISSUE THREAD

**Issue by hhugo** [ocaml-community/yojson#13]
Parsing relies on `Pervasives.float_of_string`, itself relying on `strtod`.
The issue is that `strtod` is LOCALE dependent. It may fail to parse a valid "json float" (ie. `1.3`) because it expects a `,` (coma) (ie: `1,3`)

Same issue with serialization.

Our use case:
Loading a shared library (.so written in ocaml) from a 3rd party software (that apparently use `setlocale`) results in bad parsing/printing of Json values.

**Comment by markghayden** [comment]
We have a German user on Ubuntu who can't use JSON files because the valid JSON floats won't parse in that locale.

Any progress on this?  I don't see any movement on the OCaml front.  However, while OCaml _should_ do something about this, it seems Yojson really needs to be able to operate in a locale-independent fashion.

**Comment by mjambon** [comment]
This is an unfortunate situation.

Could you @markghayden or someone else provide a complete example (code + instructions to build and run) that exhibits the problem (i.e. calls setlocale)?

**Comment by hhugo** [comment]
FYI, this should be fixed in ocaml trunk and should be part of an official release with ocaml 4.08 (due in ~6 month)

**Comment by mjambon** [comment]
@hhugo thanks for the heads up.
