### ISSUE TITLE
Stack overflow when using Yojson.Safe.pretty_to_string

### ISSUE THREAD

**Issue by rand00** [ocaml-community/yojson#144]
I'm not sure if this is relevant for you, as you have removed dependency on `easy-format` in the new version. But on the last version of `yojson` I get stack overflow when using `Yojson.Safe.pretty_to_string` instead of `Yojson.Safe.to_string`. I serialize an object containing a very big array of objects.

**Comment by rand00** [comment]
I btw. can't test with my application on the new version, as I depend on `ppx_deriving_yojson` which is not there yet

**Comment by mjambon** [comment]
@rand00 do you get a stack overflow on the same data with yojson < 2.0.0?

I'm asking because the old implementation also uses the `Format` module indirectly via easy-format, so we should be able to get the same behavior.

**Comment by rand00** [comment]
I meant that I get stack overflow on the previous version ('last version' has this meaning in danish, sorry) - i.e. 1.7.0. So I havn't tested this on version 2.0.0.

**Comment by Leonidas-from-XIV** [comment]
Not really an answer to your issue @rand00 but thanks for the reminder about `ppx_deriving_yojson`.

I was curious what it takes to make it work with Yojson 2.0 and it turns out: apparently nothing. https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/145 removes the constraint after I tested it locally and https://github.com/ocaml/opam-repository/pull/21523 removes it from older versions as well.

**Comment by rand00** [comment]
No stack overflow with v 2.0.0 (:

**Comment by Leonidas-from-XIV** [comment]
Ah, that's great to hear. Thanks for your report!
