### ISSUE TITLE
seq should only be required for old ocaml compiler version

### ISSUE THREAD

**Issue by zapashcanon** [ocaml-community/yojson#174]

**Comment by Leonidas-from-XIV** [comment]
I don't think that's (easily) possible, since one can't make dependencies conditional upon the ocaml version in dune files, one would need to use a generator checking for that and then the `opam` files would need to use templates because `dune` can't generate dependencies that depend on the compiler version. Its most likely not worth the hassle, especially since supporting older compilers is hard enough as these versions are becoming less and less common on CI, it might be easier to drop compatibility for <4.06 and use `Seq` directly.

Is there any reason why depending on `seq` is a problem for you? On newer compiler versions it compiles to a no-op, so it is identical to `Seq` from the standard library.

**Comment by zapashcanon** [comment]
It's not for me actually. Yesterday something showed-up in the [ocaml matrix room](https://matrix.to/#/#ocaml-lang:matrix.org) and was having issues because of the `seq` dependency. We managed to fix the issue but I decided to also open an issue.

**Comment by Leonidas-from-XIV** [comment]
What was the issue? If there's issues with seq, it should probably be fixed in `seq` (ping @c-cube).

**Comment by zapashcanon** [comment]
> i have this error: HEAD is now at e51163e Prepare changelog for release Running: dune build -p > yojson @install File "lib/dune", line 116, characters 12-15: 116 |  (libraries seq)                   > ^^^ Error: Library "seq" not found. -> required by library "yojson" in _build/default/lib -> required by _build/default/META.yojson -> required by _build/install/default/lib/yojson/META -> required by _build/default/yojson.install -> required by alias install Error: module yojson: Дочірній процес закінчився з кодом 1

> i'm trying to build yojson in a flatpak manifest

It was on OCaml 5.0. The solution was to do an ugly hack:

```yaml
"build-commands": [ 
  "sed -i '/libraries seq/d' lib/dune",
  "dune build -p yojson @install", 
  "dune install yojson --prefix /app" 
]  
```

**Comment by Leonidas-from-XIV** [comment]
It sounds like it's just missing a dependency (in this case `seq` but could be anything else if we had more dependencies) and is not even Yojson-specific.

I think a better way would be to figure out how to package dependencies instead of removing dependencies from Yojson.
