### ISSUE TITLE
Fix CI builds for OSX

### ISSUE THREAD

**Issue by NathanReb** [ocaml-community/yojson#70]
See [this build](https://travis-ci.org/ocaml-community/yojson/jobs/468677940) for an example failure.

**Comment by Leonidas-from-XIV** [comment]
This is due to [curl silently failing](https://github.com/ocaml/ocaml-ci-scripts/pull/278), [because it tries to download a binary](https://github.com/ocaml/ocaml-ci-scripts/issues/279) that [does not exist](https://github.com/ocaml/opam/issues/3710).

Not much yojson can do about it, it needs to be fixed either in opam or ocaml-ci-scripts.

**Comment by NathanReb** [comment]
Great thanks! I've subscribed to the relevant issues.

If that persists for too long I'll allow osx builds to fail to silence the noisy ci emails and anoly be notified when something actually goes wrong.

**Comment by NathanReb** [comment]
Last build succeeded so I assume this has been fixed upstream, closing!
