### ISSUE TITLE
solution needed for atdgen

### ISSUE THREAD

**Issue by mjambon** [ocaml-community/yojson#79]
Yojson 1.6.0 emits a deprecation warning when using the type `Yojson.Safe.json`, which is all nice and fine. However atdgen is now unhappy. Please take a look at https://github.com/mjambon/atd/issues/185

It's an interesting design problem but unfortunately I have no time to devote to this myself.

**Comment by jeromesimeon** [comment]
How about *not* deprecating the json type?

Alternatively, how about yojson providing `write_t` and `read_t` calls for consistency with atdgen?

**Comment by hcarty** [comment]
I agree that it seems worth undoing the deprecation of the `json` type.  It could still be removed in a 2.0.0 release and would undo a lot of breakage.

**Comment by NathanReb** [comment]
Before debating this further, I wish to say that I'm willing to consider undoing the deprecation warning if we can't find another satisfying way out of this.

That being said, I think there's a few things worth noting here:
1. Deprecation warnings as their name suggests are warnings and not errors and shouldn't cause build failures unless you want them to. Dune's default profile makes this warning fatal which can be a little annoying. I'm not sure what the best solution would be here as you probably don't want the noise from those warnings when you don't have actual control over the code that produces them. On the other hand you probably want to be warned about uses of deprecated types and values from your own code. Regardless of noise, I think making them fatal breaks the whole deprecation logic which is to ease the migration to the next major release.
2. Deprecating the `json` types should have been part of its own separate release so that users could enjoy the other features from `1.6.0` without caring about replacing `json` by the new `t` types. I take the blame on this one.
3. The same issue arose with `ppx_deriving_yojson`, see https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/91 and https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/90. I'd suggest a similar course of action here: add an upper bound to atdgen's yojson dependency on opam-repo, submit a PR to atdgen so it uses the new recommanded types, release a new atdgen version that depends on `yojson>=1.6.0`.

I think the core of the problem here is `1`. With the right behaviour regarding deprecation warnings we wouldn't consider the other solutions.

I'd be curious to know which build system you're using @jeromesimeon. Also I'm not really familiar with atdgen but from what I understood you're getting those warnings when generating ocaml code from your atd definitions right?

**Comment by jeromesimeon** [comment]
@NathanReb atdgen lets you define JSON types with serialization/deserialization to OCaml types. It generates a parser/serializer for you, and relies on certain conventions (T_write/T_read functions for a given type T).

I'm currently using ocamlbuild, likely will switch to dune down the road.

Yes I'm getting those warning when compiling OCaml code generated with atdgen (the linked issue has a small example if you are curious). The full atd I use is here: https://github.com/accordproject/ergo/blob/master/extraction/src/Cto.atd

A few thoughts:
- The warning is annoying, but more important is what the warning says (json type will soon be removed). [So I suppose the warning is doing its job :smile: giving advance warning to users and trigger a discussion.]
- I can't speak on how important atdgen is to other users/how pervasive a use it has, but I think this is a great library taking care of a lot of details when dealing with JSON for you (and much easier to maintain than writing serializer/deserializers by hand).

**Comment by jeromesimeon** [comment]
Note, the part of atdgen documentation that is relevant is for "untypable JSON" and can be here:
https://atd.readthedocs.io/en/latest/tutorial.html#dealing-with-untypable-json

**Comment by jeromesimeon** [comment]
I don't see https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/91 as a long term solution. Short term, I'm fine with the warnings.

**Comment by NathanReb** [comment]
I had a quick look at `atdgen` sources and from what I understood it has no specific handling of the `json` type and indeed expects to find a `write_<type_name>` in the right module, in your case `Yojson.Basic`. I didn't get that part first.

That indeed makes it hard to fix it in atdgen.

I don't think it's a good idea for `atdgen` to depend on undocumented parts of `yojson` in such a way. It's obscure and probably explain why it was so easy to "break" things in the first place.

From where I stand the warning does its job and doesn't break anything. The short term solution on your side if you need to use `yojson=1.6` seems to be the `Json` module @mjambon suggested:
```ocaml
module Json = struct
  type t = Yojson.Basic.t
  let write_t = Yojson.Basic.write_json
  let read_t = Yojson.Basic.read_json
end
```

In the meantime and for convenience I'll add `write_t` and `read_t` aliases to prevent `atdgen` users from having to define them on their own.

I think that for `2.0.0` the generic writers/readers should be exposed and documented in a specific submodule intended for people wishing to write their own parsers/printers, including `atdgen`. Modules defining a json ast type should have a `write_t` and `read_t` for compatibility with `atdgen`, exposed and documented as well.

**Comment by jeromesimeon** [comment]
@NathanReb Sounds like a good plan! Thanks.

**Comment by jeromesimeon** [comment]
Everything works great with yojson.1.7.0:
```
bash-3.2$ cat test_t.atd 
type json <ocaml module="Yojson.Safe" t="t"> = abstract
<doc text="Type of arbitrary JSON values.">

bash-3.2$ atdgen -j -j-std test_t.atd  
bash-3.2$ ocamlfind ocamlc -c test_t_j.mli -package atdgen
bash-3.2$ ocamlfind ocamlc -c test_t_j.ml -package atdgen
```
