### ISSUE TITLE
PyOn

### ISSUE THREAD

**Issue by vzaliva** [ocaml-community/yojson#94]
I need to modify JSON parser to support PyON dialect of JSON. PyON differs from JSON two ways. `None` is used instead of `null` and boolean values start with an uppercase letter as in Python. E.g. `True` and `False`.

I need this to interface with another system that uses this format. I am looking for a bit of advice on how to implement this on to of Yojson. I am mostly interested in parsing, but if it is easy enough I can implement both parsing and and printing and publish it somewhere for other people who need to use this dialect.

**Comment by Leonidas-from-XIV** [comment]
Such a change is pretty trivial to do, since the only thing that would really be affected is the lexer.

The relevant 3 lines of code are here: https://github.com/ocaml-community/yojson/blob/c0f127ac61c11046b9049223f23f9a9d3847b53a/lib/read.mll#L188-L190

So if you change it to `True`, `False` and `None` respectively you should be able to parse that weird JSON-derived format.

**Comment by vzaliva** [comment]
I figured that much. But that requires me to make a copy of whole package and changing these 3 lines. If there is a way to reuse the rest of the code? Could parser be parametrized somehow?

**Comment by Leonidas-from-XIV** [comment]
In theory it could be, but I was trying to find information about the usage of PyON and I can't find any mention of it except for a discussion on the python-ideas mailing list from 2008. Therefore I would be hesitant to add support for a non-standard format that does not seem to have any usage at all.

**Comment by vzaliva** [comment]
PyOn is part of Client API for Folding@Home project

https://github.com/FoldingAtHome/fah-control/wiki/3rd-party-FAHClient-API

This is a very popular project with more than 100,000 clients running right now https://stats.foldingathome.org/os and exposing PyOn API.

**Comment by Leonidas-from-XIV** [comment]
I could not find any users of this format, sadly, except for that one you linked (which did not show up in Google search). Unfortunately the only technical information I found was this [archived project](https://code.google.com/archive/p/pyon/) on Google Code (which is also EOL'd since a long time) and it doesn't look like a format that people would chose going forward. There is no formal specification and hardly any implementations in other languages than this 2008 project.

As such I would be very hesitant to make a JSON parser into one that parses PyON as well. It is either a new parser that will only see minimal usage and maintenance or the existing parser would silently accept invalid JSON since it parses it as PyON. That is probably not what people expect. I don't think we have the engineering resources to dedicate to PyON.

But that's no problem really, if you need that support you can just fork Yojson and make e.g. Yopyon that parses PyON. This also sets the expectation that is it a PyON parser and does not parse JSON, so you're semantically on the good side and can give PyON support all the attention that you need without having to compromise e.g. in case JSON and PyON disagree on how things should be parsed.
